### ISSUE TITLE
Building and re-installing 

### ISSUE THREAD

**Issue by trekjunky** [Zren/plasma-applet-simpleweather#10]
Building took a couple of minutes. Reinstalling is taking over an hour. I'm still waiting. Why?

**Comment by Zren** [comment]
You don't need to run the `sh ./build` script. It's used for building a `.plasmoid` for uploading to the kde store.

The `./reinstall` script uses `kpackagetool5` to update the plasmoid in `~/.local/share/plasma/plasmoids/` then restarts `plasmashell` (the panel and desktop icons + wallpaper). It should not take longer than a normal login to restart `plasmashell`.

**Comment by trekjunky** [comment]
Well, it has been over 2 hours and ./reinstall is still running. Here is a sample from the terminal that is where it is now: 
`qml: applet destroyed
kde.dataengine.mpris: "org.mpris.MediaPlayer2.chrome.instance13533" exports "SupportedMimeTypes" as D-Bus type "<unknown>" but it should be D-Bus type "as"
kde.dataengine.mpris: "org.mpris.MediaPlayer2.chrome.instance13533" exports "SupportedUriSchemes" as D-Bus type "<unknown>" but it should be D-Bus type "as"
kde.dataengine.mpris: "org.mpris.MediaPlayer2.chrome.instance13533" exports "Position" as D-Bus type "i" but it should be D-Bus type "x"
qt.qpa.xcb: QXcbConnection: XCB error: 2 (BadValue), sequence: 27161, resource id: 75497478, major code: 142 (Unknown), minor code: 3
libkcups: Renew-Subscription last error: 0 successful-ok
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:334: Unable to assign [undefined] to int
qt.qpa.xcb: QXcbConnection: XCB error: 2 (BadValue), sequence: 41766, resource id: 29360133, major code: 142 (Unknown), minor code: 3
qt.qpa.xcb: QXcbConnection: XCB error: 2 (BadValue), sequence: 41840, resource id: 75497478, major code: 142 (Unknown), minor code: 3
qt.qpa.xcb: QXcbConnection: XCB error: 2 (BadValue), sequence: 41855, resource id: 29360133, major code: 142 (Unknown), minor code: 3
qt.qpa.xcb: QXcbConnection: XCB error: 2 (BadValue), sequence: 42017, resource id: 75497478, major code: 142 (Unknown), minor code: 3
qt.qpa.xcb: QXcbConnection: XCB error: 2 (BadValue), sequence: 42063, resource id: 29360133, major code: 142 (Unknown), minor code: 3
qt.qpa.xcb: QXcbConnection: XCB error: 2 (BadValue), sequence: 42143, resource id: 75497478, major code: 142 (Unknown), minor code: 3
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 43701, resource id: 29360133, major code: 142 (Unknown), minor code: 3
qt.qpa.xcb: QXcbConnection: XCB error: 152 (Unknown), sequence: 43702, resource id: 111151371, major code: 143 (Unknown), minor code: 2`

**Comment by Zren** [comment]
Try `plasmashell --replace`. We used `killall plasmashell; kstart5 plasmashell` which might have caused an issue. I've no idea how OpenSUSE normally starts `plasmashell` so maybe something broke. The script is trying to restart plasma without logging out and back in, so maybe try just doing that?

What does the output of these commands look like?

```bash
ls ~/.local/share/plasma/plasmoids/
ls -R ~/.local/share/plasma/plasmoids/com.github.zren.simpleweather/
```

**Comment by trekjunky** [comment]
I deleted rm -R ~/.local/share/plasma/plasmoids/com.github.zren.simpleweather/ and ran ./install. It took just a second, and the widget works now, BUT when I resize it, It crashes KDE.

**Comment by Zren** [comment]
This was likely related to your other issue (Issue #9), so closing.
