### ISSUE TITLE
Add an option for reversing the color

### ISSUE THREAD

**Issue by trmdi** [Zren/plasma-applet-simpleweather#11]
Currently it uses theme.textColor, that is ok when you have the widget's background. But in the case you hide it and the wallpaper color is similar to the textColor, it's not really good.

So I suggest to add an option like that.

**Comment by Zren** [comment]
Added the ability to set the text color, and toggle an outline which defaults to using the `theme.backgroundColor`.

![2019-07-24___21-24-18](https://user-images.githubusercontent.com/416367/61838893-674e0700-ae59-11e9-9b9c-91ef43e1d287.png)

**Comment by Zren** [comment]
v6 is released with this feature.
