### ISSUE TITLE
If wifi disconnects, simpleweather freezes with temp at time of disconnection

### ISSUE THREAD

**Issue by trekjunky** [Zren/plasma-applet-simpleweather#12]
How can I force simple weather to refresh and continue to connect to the internet again? I tried to open the configuration window and click OK but that doesn't help.

**Comment by trekjunky** [comment]
The only thing that works is logging out of KDE and logging back in again.

**Comment by trekjunky** [comment]
I was really hoping for a solution/update that would allow me to manually update the weather,

**Comment by trekjunky** [comment]
If you don't answer me, I will go with another plasma weather provider

**Comment by Zren** [comment]
I'm reusing the default weather widget code. It doesn't really have a way to force a refresh that I can see.

**Comment by Zren** [comment]
I've disconnected my ethernet before 2PM, waited half an hour with it not connect. This is with Plasma 5.18 Beta (though i don't think I noticed this in Plasma 5.17). I'm using envcan source.

The weather dataengine does have code for rechecking weather when it reconnects to the internet.

* https://github.com/KDE/plasma-workspace/blame/master/dataengines/weather/weatherengine.cpp#L174
* https://github.com/KDE/plasma-workspace/commits/master/dataengines/weather/weatherengine.cpp
* https://github.com/KDE/plasma-workspace/blame/master/dataengines/weather/weatherengine.h
* https://github.com/KDE/plasma-framework/blob/master/src/plasma/dataengine.h
